//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterLevelIndicator.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WaterLevelIndicationDBEntities1 : DbContext
    {
        public WaterLevelIndicationDBEntities1()
            : base("name=WaterLevelIndicationDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WaterLevelData> WaterLevelDatas { get; set; }
        public virtual DbSet<WaterLevelIndicationUser> WaterLevelIndicationUsers { get; set; }
    }
}
