//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterLevelIndicator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaterLevelData
    {
        public int ID { get; set; }
        public Nullable<int> BoxID { get; set; }
        public Nullable<decimal> Measurement { get; set; }
        public Nullable<System.DateTime> MeasurementDateTime { get; set; }
        public string TriggerStatus { get; set; }
        public string Label { get; set; }
    }
}
